<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estado_entrega extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Estado_entrega_model');
        $this->load->library('session');
    } 

    /*
     * Listing of estado_entrega
     */
    function index()
    {
        $data['estado_entrega'] = $this->Estado_entrega_model->get_all_estado_entrega();
        
        $data['_view'] = 'estado_entrega/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new estado_entrega
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre_estado' => $this->input->post('nombre_estado'),
            );
            
            $estado_entrega_id = $this->Estado_entrega_model->add_estado_entrega($params);
            redirect('estado_entrega/index');
        }
        else
        {            
            $data['_view'] = 'estado_entrega/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a estado_entrega
     */
    function edit($id_estado_entrega)
    {   
        // check if the estado_entrega exists before trying to edit it
        $data['estado_entrega'] = $this->Estado_entrega_model->get_estado_entrega($id_estado_entrega);
        
        if(isset($data['estado_entrega']['id_estado_entrega']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre_estado' => $this->input->post('nombre_estado'),
                );

                $this->Estado_entrega_model->update_estado_entrega($id_estado_entrega,$params);            
                redirect('estado_entrega/index');
            }
            else
            {
                $data['_view'] = 'estado_entrega/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The estado_entrega you are trying to edit does not exist.');
    } 

    /*
     * Deleting estado_entrega
     */
    function remove($id_estado_entrega)
    {
        $estado_entrega = $this->Estado_entrega_model->get_estado_entrega($id_estado_entrega);

        // check if the estado_entrega exists before trying to delete it
        if(isset($estado_entrega['id_estado_entrega']))
        {
            $this->Estado_entrega_model->delete_estado_entrega($id_estado_entrega);
            redirect('estado_entrega/index');
        }
        else
            show_error('The estado_entrega you are trying to delete does not exist.');
    }
    
}
