<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Evolucion_vale extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Evolucion_vale_model');
    } 

    /*
     * Listing of evolucion_vale
     */
    function index()
    {
        $data['evolucion_vale'] = $this->Evolucion_vale_model->get_all_evolucion_vale();
        
        $data['_view'] = 'evolucion_vale/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new evolucion_vale
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_vale' => $this->input->post('id_vale'),
				'id_estado' => $this->input->post('id_estado'),
				'fecha' => $this->input->post('fecha'),
				'hora' => $this->input->post('hora'),
				'id_responsable' => $this->input->post('id_responsable'),
				'observacion' => $this->input->post('observacion'),
            );
            
            $evolucion_vale_id = $this->Evolucion_vale_model->add_evolucion_vale($params);
            redirect('evolucion_vale/index');
        }
        else
        {            
            $data['_view'] = 'evolucion_vale/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a evolucion_vale
     */
    function edit($)
    {   
        // check if the evolucion_vale exists before trying to edit it
        $data['evolucion_vale'] = $this->Evolucion_vale_model->get_evolucion_vale($);
        
        if(isset($data['evolucion_vale']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_vale' => $this->input->post('id_vale'),
					'id_estado' => $this->input->post('id_estado'),
					'fecha' => $this->input->post('fecha'),
					'hora' => $this->input->post('hora'),
					'id_responsable' => $this->input->post('id_responsable'),
					'observacion' => $this->input->post('observacion'),
                );

                $this->Evolucion_vale_model->update_evolucion_vale($,$params);            
                redirect('evolucion_vale/index');
            }
            else
            {
                $data['_view'] = 'evolucion_vale/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The evolucion_vale you are trying to edit does not exist.');
    } 

    /*
     * Deleting evolucion_vale
     */
    function remove($)
    {
        $evolucion_vale = $this->Evolucion_vale_model->get_evolucion_vale($);

        // check if the evolucion_vale exists before trying to delete it
        if(isset($evolucion_vale['']))
        {
            $this->Evolucion_vale_model->delete_evolucion_vale($);
            redirect('evolucion_vale/index');
        }
        else
            show_error('The evolucion_vale you are trying to delete does not exist.');
    }
    
}
