<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Fk_categoria extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fk_categoria_model');
        $this->user = $this->ion_auth->user()->row();
        $this->data = $this->generales->imports_generales();

        if(!$this->ion_auth->in_group($this->config->item('Administrator'))){
        $this->session->set_flashdata('error', 'No Tiene permisos para realizar esta acción');
        redirect('/');
  }
    }

    /*
     * Listing of fk_categorias
     */
    function index()
    {
        $this->data['fk_categorias'] = $this->Fk_categoria_model->get_all_fk_categorias_all();

        $this->data['_view'] = 'fk_categoria/index';
        $this->load->view('layouts/main',$this->data);
    }

    /*
     * Adding a new fk_categoria
     */
    function add()
    {
        $this->load->library('form_validation');

    		$this->form_validation->set_rules('codigo_categoria','Codigo Categoria','required');
    		$this->form_validation->set_rules('nombre_categoria','Nombre Categoria','required|exact_length[3]');

		if($this->form_validation->run())
        {
            $params = array(
      				'codigo_categoria' => $this->input->post('codigo_categoria'),
      				'nombre_categoria' => $this->input->post('nombre_categoria'),
      				'descripcion_categoria' => $this->input->post('descripcion_categoria'),
              'status'        => $this->config->item('Activo'),
            );

            $fk_categoria_id = $this->Fk_categoria_model->add_fk_categoria($params);
            redirect('fk_categoria/index');
        }
        else
        {
            $this->data['_view'] = 'fk_categoria/add';
            $this->load->view('layouts/main',$this->data);
        }
    }

    function get_all_fk_categorias_codigo(){
      echo json_encode($this->Fk_categoria_model->get_all_fk_categorias_codigo($this->input->POST('search')));
    }

    /*
     * Editing a fk_categoria
     */
    function edit($id_fk_categoria)
    {
        // check if the fk_categoria exists before trying to edit it
        $this->data['fk_categoria'] = $this->Fk_categoria_model->get_fk_categoria($id_fk_categoria);

        if(isset($this->data['fk_categoria']['id_fk_categoria']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('codigo_categoria','Codigo Categoria','required');
			$this->form_validation->set_rules('nombre_categoria','Nombre Categoria','required|exact_length[3]');

			if($this->form_validation->run())
            {
                $params = array(
					'codigo_categoria' => $this->input->post('codigo_categoria'),
					'nombre_categoria' => $this->input->post('nombre_categoria'),
					'descripcion_categoria' => $this->input->post('descripcion_categoria'),
                );

                $this->Fk_categoria_model->update_fk_categoria($id_fk_categoria,$params);
                redirect('fk_categoria/index');
            }
            else
            {
                $this->data['_view'] = 'fk_categoria/edit';
                $this->load->view('layouts/main',$this->data);
            }
        }
        else
            show_error('The fk_categoria you are trying to edit does not exist.');
    }

    /*
     * Deleting fk_categoria
     */
    function remove($id_fk_categoria)
    {
      $fk_categoria = $this->Fk_categoria_model->get_fk_categoria($id_fk_categoria);

      // check if the sector_req exists before trying to delete it
      if(isset($fk_categoria['id_fk_categoria']))
      {
        if($fk_categoria['status'] == $this->config->item('Inactivo')){
            $array = array(
                'status' => $this->config->item('Activo')
            );
        }else{
            $array = array(
                'status' => $this->config->item('Inactivo')
            );
        }
          $this->Fk_categoria_model->update_fk_categoria($fk_categoria['id_fk_categoria'],$array);
          redirect('fk_categoria/index');
      }
      else
          show_error('The fk_motivo you are trying to delete does not exist.');
    }

}
