<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Fk_categorias_lm extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fk_categorias_lm_model');
        $this->user = $this->ion_auth->user()->row();
        $this->data = $this->generales->imports_generales();

        if(!$this->ion_auth->in_group($this->config->item('Administrator'))){
        $this->session->set_flashdata('error', 'No Tiene permisos para realizar esta acción');
        redirect('/');
  }
    }

    /*
     * Listing of fk_categorias_lm
     */
    function index()
    {
        $this->data['fk_categorias_lm'] = $this->Fk_categorias_lm_model->get_all_fk_categorias_lm();

        $this->data['_view'] = 'fk_categorias_lm/index';
        $this->load->view('layouts/main',$this->data);
    }

    /*
     * Adding a new fk_categorias_lm
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nom_cat_lm','Nom Cat Lm','min_length[2]|max_length[6]');

		if($this->form_validation->run())
        {
            $params = array(
				'nom_cat_lm' => $this->input->post('nom_cat_lm'),
				'cod_cat_lm' => $this->input->post('cod_cat_lm'),
				'obs_cat_lm' => $this->input->post('obs_cat_lm'),
        'status_cat_lm' => $this->config->item('Activo'),
            );

            $fk_categorias_lm_id = $this->Fk_categorias_lm_model->add_fk_categorias_lm($params);
            redirect('fk_categorias_lm/index');
        }
        else
        {
            $this->data['_view'] = 'fk_categorias_lm/add';
            $this->load->view('layouts/main',$this->data);
        }
    }

    /*
     * Editing a fk_categorias_lm
     */
    function edit($id_cat_lm)
    {
        // check if the fk_categorias_lm exists before trying to edit it
        $data['fk_categorias_lm'] = $this->Fk_categorias_lm_model->get_fk_categorias_lm($id_cat_lm);

        if(isset($data['fk_categorias_lm']['id_cat_lm']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nom_cat_lm','Nom Cat Lm','min_length[2]|max_length[6]');

			if($this->form_validation->run())
            {
                $params = array(
					'nom_cat_lm' => $this->input->post('nom_cat_lm'),
					'cod_cat_lm' => $this->input->post('cod_cat_lm'),
					'obs_cat_lm' => $this->input->post('obs_cat_lm'),
                );

                $this->Fk_categorias_lm_model->update_fk_categorias_lm($id_cat_lm,$params);
                redirect('fk_categorias_lm/index');
            }
            else
            {
                $this->data['_view'] = 'fk_categorias_lm/edit';
                $this->load->view('layouts/main',$this->data);
            }
        }
        else
            show_error('The fk_categorias_lm you are trying to edit does not exist.');
    }

    /*
     * Deleting fk_categoria
     */
    function remove($id_fk_categoria)
    {
      $fk_categoria_lm = $this->Fk_categorias_lm_model->get_fk_categorias_lm($id_fk_categoria);

      // check if the sector_req exists before trying to delete it
      if(isset($fk_categoria_lm['id_cat_lm']))
      {
        if($fk_categoria_lm['status_cat_lm'] == $this->config->item('Inactivo')){
            $array = array(
                'status_cat_lm' => $this->config->item('Activo')
            );
        }else{
            $array = array(
                'status_cat_lm' => $this->config->item('Inactivo')
            );
        }
          $this->Fk_categorias_lm_model->update_fk_categorias_lm($fk_categoria_lm['id_cat_lm'],$array);
          redirect('fk_categorias_lm/index');
      }
      else
          show_error('The fk_motivo you are trying to delete does not exist.');
    }
}
