<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Fk_motivo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fk_motivo_model');
        $this->user = $this->ion_auth->user()->row();
        $this->data = $this->generales->imports_generales();

          if(!$this->ion_auth->in_group($this->config->item('Administrator'))){
            $this->session->set_flashdata('error', 'No Tiene permisos para realizar esta acción');
                    redirect('/');
          }


    }

    /*
     * Listing of fk_motivo
     */
    function index()
    {
        $this->data['fk_motivo'] = $this->Fk_motivo_model->get_all_fk_motivo_all();
        $this->data['_view'] = 'fk_motivo/index';
        $this->load->view('layouts/main',$this->data);
    }

    /*
     * Adding a new fk_motivo
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre_motivo','Nombre Motivo','required');
        $this->form_validation->set_rules('cod_jde','Código JDE','required');
		if($this->form_validation->run())
        {
            $params = array(
                'cod_jde'       => $this->input->post('cod_jde'),
				'nombre_motivo' => $this->input->post('nombre_motivo'),
                'descripcion'       => $this->input->post('descripcion'),
                'status'        => $this->config->item('Activo'),
            );

            $fk_motivo_id = $this->Fk_motivo_model->add_fk_motivo($params);
            redirect('fk_motivo/index');
        }
        else
        {
            $this->data['_view'] = 'fk_motivo/add';
            $this->load->view('layouts/main',$this->data);
        }
    }

    /*
     * Editing a fk_motivo
     */
    function edit($id_motivo)
    {
        // check if the fk_motivo exists before trying to edit it
        $this->data['fk_motivo'] = $this->Fk_motivo_model->get_fk_motivo($id_motivo);

        if(isset($this->data['fk_motivo']['id_motivo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre_motivo','Nombre Motivo','required');
            $this->form_validation->set_rules('cod_jde','Código JDE','required');

			if($this->form_validation->run())
            {
                $params = array(
                    'cod_jde'       => $this->input->post('cod_jde'),
                    'descripcion'       => $this->input->post('descripcion'),
					'nombre_motivo' => $this->input->post('nombre_motivo'),
                );

                $this->Fk_motivo_model->update_fk_motivo($id_motivo,$params);
                redirect('fk_motivo/index');
            }
            else
            {
                $this->data['_view'] = 'fk_motivo/edit';
                $this->load->view('layouts/main',$this->data);
            }
        }
        else
            show_error('The fk_motivo you are trying to edit does not exist.');
    }

    /*
     * Deleting fk_motivo
     */
    function remove($id_motivo)
    {
              $fk_motivo = $this->Fk_motivo_model->get_fk_motivo($id_motivo);

              // check if the sector_req exists before trying to delete it
              if(isset($fk_motivo['id_motivo']))
              {
                if($fk_motivo['status'] == $this->config->item('Inactivo')){
                    $array = array(
                        'status' => $this->config->item('Activo')
                    );
                }else{
                    $array = array(
                        'status' => $this->config->item('Inactivo')
                    );
                }
                  $this->Fk_motivo_model->update_fk_motivo($fk_motivo['id_motivo'],$array);
                  redirect('fk_motivo/index');
              }
              else
                  show_error('The fk_motivo you are trying to delete does not exist.');
            }
}
