<?php

/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Reportes extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Articulo_model');
        $this->load->model('Vales_consumo_model');
        $this->load->helper('date');
        $this->load->model('Fk_un_med_model');
        $this->load->model('Fk_categoria_model');
        $this->load->model('Fk_categorias_lm_model');

        $this->data = $this->generales->imports_generales();

        //aca valido que solo ciertos perfiles de usuarios puedan utilizar los metodos de estre controlador

        if(!$this->ion_auth->in_group($this->config->item('Administrator'))){
          $this->session->set_flashdata('error','No tiene permiso para realizar esta acción1.11111');
                 redirect('/');

        }
    }

    public function ReporteVales(){
            $this->data['_view'] = 'reportes/vales';
            $this->load->view('layouts/main',$this->data);
    }
    public function ReporteTransferencias(){
            $this->data['_view'] = 'reportes/transferencias';
            $this->load->view('layouts/main',$this->data);
    }

    public function test(){
        echo json_encode($this->Vales_consumo_model->get_report(strtotime($this->input->post('from')),strtotime($this->input->post('to')),$this->input->post('sucursal')));
    }

}
