<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Role extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->library('ion_auth');
        $this->load->library('session');   
        $this->load->model('Role_model');
    } 

    /*
     * Listing of roles
     */
    function index()
    {
        $user = $this->ion_auth->user()->row();
        $data['user'] = $user;
            if($this->ion_auth->loginCheck() && $this->ion_auth->RolCheck($user->id, $this->config->item('AdministrarRoles'))){
            $data['roles'] = $this->Role_model->get_all_roles();
                $data['_view'] = 'role/index';
                $this->load->view('layouts/main',$data);
    }
}

    /*
     * Adding a new role
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre_rol' => $this->input->post('nombre_rol'),
				'descripcion_rol' => $this->input->post('descripcion_rol'),
            );
            
            $role_id = $this->Role_model->add_role($params);
            redirect('role/index');
        }
        else
        {            
            $data['_view'] = 'role/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a role
     */
    function edit($id_rol)
    {   
        // check if the role exists before trying to edit it
        $data['role'] = $this->Role_model->get_role($id_rol);
        
        if(isset($data['role']['id_rol']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre_rol' => $this->input->post('nombre_rol'),
					'descripcion_rol' => $this->input->post('descripcion_rol'),
                );

                $this->Role_model->update_role($id_rol,$params);            
                redirect('role/index');
            }
            else
            {
                $data['_view'] = 'role/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The role you are trying to edit does not exist.');
    } 

    /*
     * Deleting role
     */
    function remove($id_rol)
    {
        $role = $this->Role_model->get_role($id_rol);

        // check if the role exists before trying to delete it
        if(isset($role['id_rol']))
        {
            $this->Role_model->delete_role($id_rol);
            redirect('role/index');
        }
        else
            show_error('The role you are trying to delete does not exist.');
    }
    
}
