<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Roles_group extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Roles_group_model');
        $this->load->library('ion_auth');
        $this->load->library('session');
        $this->load->model('Vales_consumo_model');  
        $this->load->model('Jerarquia_model');
    
         
         $this->user = $this->ion_auth->user()->row();
         $this->data['sesion'] = $this->user; 
         $this->data['aprobaciones_barra'] =  $this->Vales_consumo_model->get_all_vales_count($this->config->item('Pendiente'),$this->config->item('PendienteDeAprobacion'));
         $this->data['estado_barra'] =  $this->Vales_consumo_model->get_all_vales_count($this->config->item('Aprobado'),$this->config->item('EnProcesoDeArmado'), $this->Jerarquia_model->get_sector_user($this->user->id));
    } 

    /*
     * Listing of roles_group
     */
    function index()
    {
        $this->data['roles_group'] = $this->Roles_group_model->get_all_roles_group();
        
        $this->data['_view'] = 'roles_group/index';
        $this->load->view('layouts/main',$this->data);
    }

    /*
     * Adding a new roles_group
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'role_id' => $this->input->post('rol_id'),
            );
            
            $roles_group_id = $this->Roles_group_model->add_roles_group($params);
            redirect('roles_group/index');
        }
        else
        {
			$this->load->model('User_model');
			$this->data['all_users'] = $this->User_model->get_all_users();

			$this->load->model('Role_model');
			$this->data['all_roles'] = $this->Role_model->get_all_roles();
            
            $this->data['_view'] = 'roles_group/add';
            $this->load->view('layouts/main',$this->data);
        }
    }  

    /*
     * Editing a roles_group
     */
    function edit($id)
    {   
        // check if the roles_group exists before trying to edit it
        $data['roles_group'] = $this->Roles_group_model->get_roles_group($id);
        
        if(isset($data['roles_group']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'rol_id' => $this->input->post('rol_id'),
                );

                $this->Roles_group_model->update_roles_group($id,$params);            
                redirect('roles_group/index');
            }
            else
            {
				$this->load->model('User_model');
				$this->data['all_users'] = $this->User_model->get_all_users();

				$this->load->model('Role_model');
				$this->data['all_roles'] = $this->Role_model->get_all_roles();

                $this->data['_view'] = 'roles_group/edit';
                $this->load->view('layouts/main',$this->data);
            }
        }
        else
            show_error('The roles_group you are trying to edit does not exist.');
    } 

    /*
     * Deleting roles_group
     */
    function remove($id)
    {
        $roles_group = $this->Roles_group_model->get_roles_group($id);

        // check if the roles_group exists before trying to delete it
        if(isset($roles_group['']))
        {
            $this->Roles_group_model->delete_roles_group($id);
            redirect('roles_group/index');
        }
        else
            show_error('The roles_group you are trying to delete does not exist.');
    }
    
}
