<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Estado_entrega_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get estado_entrega by id_estado_entrega
     */
    function get_estado_entrega($id_estado_entrega)
    {
        return $this->db->get_where('estado_entrega',array('id_estado_entrega'=>$id_estado_entrega))->row();
    }

    /*
     * Get all estado_entrega
     */
    function get_all_estado_entrega()
    {
        $this->db->order_by('id_estado_entrega', 'asc');
        return $this->db->get('estado_entrega')->result_array();
    }

      function get_all_estado_aprobacion()
    {
        $this->db->order_by('id_estado_aprobacion_fk', 'asc');
        return $this->db->get('estado_aprobacion')->result_array();
    }




    /*
     * function to add new estado_entrega
     */
    function add_estado_entrega($params)
    {
        $this->db->insert('estado_entrega',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update estado_entrega
     */
    function update_estado_entrega($id_estado_entrega,$params)
    {
        $this->db->where('id_estado_entrega',$id_estado_entrega);
        return $this->db->update('estado_entrega',$params);
    }

    /*
     * function to delete estado_entrega
     */
    function delete_estado_entrega($id_estado_entrega)
    {
        return $this->db->delete('estado_entrega',array('id_estado_entrega'=>$id_estado_entrega));
    }
}
