<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Fk_categorias_lm_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get fk_categorias_lm by id_cat_lm
     */
    function get_fk_categorias_lm($id_cat_lm)
    {
        return $this->db->get_where('fk_categorias_lm',array('id_cat_lm'=>$id_cat_lm))->row_array();
    }

    /*
     * Get fk_un_med by id_un_medida
     */
    function get_fk_cat_by_name($nombre_cat)
    {
        return $this->db->get_where('fk_categorias_lm',array('nom_cat_lm'=>$nombre_cat))->row_array()['id_cat_lm'];
    }

    /*
     * Get all fk_categorias_lm
     */
    function get_all_fk_categorias_lm()
    {
        $this->db->order_by('id_cat_lm', 'desc');
        return $this->db->get('fk_categorias_lm')->result_array();
    }

    /*
     * function to add new fk_categorias_lm
     */
    function add_fk_categorias_lm($params)
    {
        $this->db->insert('fk_categorias_lm',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update fk_categorias_lm
     */
    function update_fk_categorias_lm($id_cat_lm,$params)
    {
        $this->db->where('id_cat_lm',$id_cat_lm);
        return $this->db->update('fk_categorias_lm',$params);
    }

    /*
     * function to delete fk_categorias_lm
     */
    function delete_fk_categorias_lm($id_cat_lm)
    {
        return $this->db->delete('fk_categorias_lm',array('id_cat_lm'=>$id_cat_lm));
    }
}
