<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Fk_motivo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get fk_motivo by id_motivo
     */
    function get_fk_motivo($id_motivo)
    {
        return $this->db->get_where('fk_motivo',array('id_motivo'=>$id_motivo))->row_array();
    }


    function get_all_fk_motivo_all()
    {
        $this->db->where('id_motivo !=', $this->config->item('Inactivo'));
        $this->db->order_by('id_motivo', 'asc');
        return $this->db->get('fk_motivo')->result_array();
    }
    /*
     * Traigo todos los motivos que estan activos, menos el que tiene id 0, que es el motivo de vales de m. prima.
     */
    function get_all_fk_motivo()
    {
        $this->db->where('id_motivo !=', $this->config->item('Inactivo'));
        $this->db->where('status', $this->config->item('Activo'));
        $this->db->order_by('id_motivo', 'asc');
        return $this->db->get('fk_motivo')->result_array();
    }
    /*
     * Traigo solo el motivo que es para mprima
     */
    function get_all_fk_motivo_mat_prima()
    {
        $this->db->where('id_motivo', $this->config->item('Inactivo'));
        return $this->db->get('fk_motivo')->result_array();
    }



    /*
     * function to add new fk_motivo
     */
    function add_fk_motivo($params)
    {
        $this->db->insert('fk_motivo',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update fk_motivo
     */
    function update_fk_motivo($id_motivo,$params)
    {
        $this->db->where('id_motivo',$id_motivo);
        return $this->db->update('fk_motivo',$params);
    }

    /*
     * function to delete fk_motivo
     */
    function delete_fk_motivo($id_motivo)
    {
        return $this->db->delete('fk_motivo',array('id_motivo'=>$id_motivo));
    }
}
