<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Jerarquia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get jerarquia by id_jerarquia
     */
    function get_jerarquia($id_jerarquia)
    {
        return $this->db->get_where('jerarquias',array('id_jerarquia'=>$id_jerarquia))->row_array();
    }

    /*
     * Get all jerarquias count
     */
    function get_all_jerarquias_count($params = null)
    {
        $this->db->from('jerarquias');
        if(isset($params['user']) && !empty($params['user']))
        {
            $this->db->where('id_user_padre', $params['user']);
        }
        return $this->db->count_all_results();
    }

    /*
     * Get all jerarquias
     */
    function get_all_jerarquias($params = array())
    {



        $this->db->select('users.username AS user_padre');

        $this->db->select('id_jerarquia, id_sector_jerarquia, first_name, last_name, nombre_sector, id_sector_req, users_groups.group_id, groups.description');
        $this->db->join('users ', 'users.id = id_user_padre');
        $this->db->join('sector_req','id_sector_req = id_sector_jerarquia');
        $this->db->join('users_groups  ','users_groups.user_id = users.id');
        $this->db->join('groups', 'groups.id = users_groups.group_id' );
          if(isset($params['limit']) && !empty($params['limit']))
          {
              $this->db->limit($params['limit'], $params['offset']);
          }
            if(isset($params['user']) && !empty($params['user']))
            {
                $this->db->where('id_user_padre', $params['user']);
            }
              if(isset($params['sector']) && !empty($params['sector']))
              {
                  $this->db->where('id_sector_jerarquia', $params['sector']);
              }
              $this->db->order_by("id_sector_req", "asc");
        return $this->db->get('jerarquias')->result_array();
    }

    /*
     * function to add new jerarquia
     */
    function add_jerarquia($params)
    {
        $this->db->insert('jerarquias',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update jerarquia
     */
    function update_jerarquia($id_jerarquia,$params)
    {
        $this->db->where('id_jerarquia',$id_jerarquia);
        return $this->db->update('jerarquias',$params);
    }

    /*
     * function to delete jerarquia
     */
    function delete_jerarquia($id_jerarquia)
    {
        return $this->db->delete('jerarquias',array('id_jerarquia'=>$id_jerarquia));
    }

    /*

    Usos:
        * Alta de nuevos Vales


    */

    function get_sector_user($id_user){
        $this->db->join('sector_req', 'id_sector_req = id_sector_jerarquia');
        $this->db->where('status_sector', $this->config->item('Activo'));
        return $this->db->get_where('jerarquias',array('id_user_padre'=>$id_user))->result();
    }


/*
*   Esta Funcion devuelve un objeto con la informacion del usuario que es Aprobador/Pañolero de un determinado sector
*
*
*/
    function get_responsible_by_sector($id_sector){

        $this->db->join('users ', 'users.id = id_user_padre');
        $this->db->join('users_groups  ','users_groups.user_id = users.id');
        $this->db->join('groups', 'groups.id = users_groups.group_id' );
        $this->db->join('sector_req','id_sector_req = id_sector_jerarquia');
        $this->db->where('id_sector_jerarquia',$id_sector);
        //
        $this->db->where_in('groups.id', $this->config->item('Mail_Aprobacion'));
        return $this->db->get('jerarquias')->result();

    }



function query($query){
    $query = $this->db->query($query);
    return $query->result();
    }





}
