<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Notificaciones_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get notificaciones_user by id_notificaciones_users
     */
    function get_notificaciones_user($id_notificaciones_users)
    {

        return $this->db->get_where('notificaciones_users',array('id_notificaciones_users'=>$id_notificaciones_users))->row_array();
    }

    /*
     * Get notificaciones_user by id_notificaciones_users
     */
    function get_notificaciones_by_user_id($id_users)
    {
        return $this->db->get_where('notificaciones_users',array('user_id'=>$id_users))->row_array();
    }

    /*
     * Get all notificaciones_users
     */
    function get_all_notificaciones_users()
    {
        $this->db->join('users ', 'users.id = user_id');
        $this->db->order_by('id_notificaciones_users', 'desc');
        $this->db->where('users.active',1);
        return $this->db->get('notificaciones_users')->result_array();
    }

    /*
     * function to add new notificaciones_user
     */
    function add_notificaciones_user($params)
    {
        $this->db->insert('notificaciones_users',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update notificaciones_user
     */
    function update_notificaciones_user($id_notificaciones_users,$params)
    {
        $this->db->where('id_notificaciones_users',$id_notificaciones_users);
        return $this->db->update('notificaciones_users',$params);
    }

    /*
     * function to delete notificaciones_user
     */
    function delete_notificaciones_user($id_notificaciones_users)
    {
        return $this->db->delete('notificaciones_users',array('id_notificaciones_users'=>$id_notificaciones_users));
    }

    function get_notifications_settings($id_user, $id_event){
        $array = array(
            'user_id' => $id_user,
            $id_event => TRUE
        );


        $this->db->from('notificaciones_users');
        $this->db->where($array);

        $result = $this->db->count_all_results();
        if ($result && $result > 0) {
            return TRUE;
        } else {
            return FALSE;
        }
      }
}
